# Site settings
title: Liam R. Carroll
author:
  name: Liam R. Carroll, 2021
  email: Liam.Robert.Carroll@gmail.com
description: "Stuff I find interesting"



# Build settings
remote_theme: jekyll/minima

# This turns on dark mode

