# Site settings
title: Liam R. Carroll
author:
  name: Liam R. Carroll, 2021
  email: Liam.Robert.Carroll@gmail.com
description: "Stuff I find interesting"

show_excerpts: true # set to true to show excerpts on the homepage


# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag



# This turns on dark mode
#minima:
 # skin: dark
