# Site settings
title: Liam R. Carroll
author:
  name: Liam R. Carroll, 2021
  email: Liam.Robert.Carroll@gmail.com
description: "Stuff I find interesting"
url: LRCarroll.github.io
baseurl: /Website/
show_excerpts: False # set to true to show excerpts on the homepage


# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-relative-links



# This turns on dark mode
#minima:
  #skin: dark
