# Site settings
title: Liam R. Carroll
author:
  name: Liam R. Carroll, 2021
  email: Liam.Robert.Carroll@gmail.com
description: "Stuff I find interesting"



# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

minima:
  skin: dark

# This turns on dark mode

